name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Setup Python          
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install Poetry Action        
      uses: snok/install-poetry@v1.3.4


    - name: poetry install
      run: poetry install
    - name: run macli
      run: poetry run macli --help

    - name: Build with Gradle
      run: chmod +x android/gradlew && cd android ; ./gradlew build
